spring:
  datasource:
    url: ${DB_URL} # jdbc:mysql://localhost:3306/jdon?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME} #root
    password: ${DB_PASSWORD} #1234

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        #        show-sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace
  org.springframework.security: debug
