spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:1221/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email
          github:
            client-name: github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: http://localhost:1221/login/oauth2/code/github
            scope: user:email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    web:
      pageable:
        max-page-size: 100

logging:
  level:
    root: info

decorator:
  datasource:
    p6spy:
      enable-logging: true

custom-oauth2:
  kakao:
    app-admin-key: ${KAKAO_APP_ADMIN_KEY}
    delete-user-url: https://kapi.kakao.com/v1/user/unlink

allowed-origins:
  origin: http://localhost:3000/
  url-list:
    - "http://localhost:3000"
    - "https://localhost:3000"
    - "https://jdon.kr"
    - "https://dev.jdon.kr"
  ip:
    monitoring-list:
      - "3.34.69.116"
      - "0:0:0:0:0:0:0:1"

# http://localhost:3000
redirect-url:
  login:
    success:
      member: http://localhost:3000/oauth/login/success
      guest: http://localhost:3000/oauth/info?
    failure:
      not-found-email: http://localhost:3000/oauth/login/fail/not-found-email
      not-match-provider: http://localhost:3000/oauth/login/fail/not-match-provider
      another-withdraw-account: http://localhost:3000/oauth/login/fail/another-withdraw-account
      already-withdraw-account: http://localhost:3000/oauth/login/fail/already-withdraw-account

redis:
  lock:
    coffee-chat:
      wait-time: 5
      lease-time: 1

crypto:
  aes-private-key: JDON_SECRET_KEY_AES_USE_THIS_KEY
  hmac-private-key: JDON_SECRET_KEY_HMAC_USE_THIS_KK

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: