spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://api.jdon.kr/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email
          github:
            client-name: github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: https://api.jdon.kr/login/oauth2/code/github
            scope: user:email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    web:
      pageable:
        max-page-size: 100
    redis:
      port: 6379
      host: 127.0.0.1
      password: ${REDIS_PASSWORD}


logging:
  level:
    root: info

decorator:
  datasource:
    p6spy:
      enable-logging: true

custom-oauth2:
  kakao:
    app-admin-key: ${KAKAO_APP_ADMIN_KEY}
    delete-user-url: https://kapi.kakao.com/v1/user/unlink

redirect-url:
  login:
    success:
      member: https://jdon.kr/oauth/login/success
      guest: https://jdon.kr/oauth/info?
    failure:
      not-found-email: https://jdon.kr/oauth/login/fail/not-found-email
      not-match-provider: https://jdon.kr/oauth/login/fail/not-match-provider
  logout:
    success: https://jdon.kr

redis:
  lock:
    coffee-chat:
      wait-time: 5
      lease-time: 1
