name: Java CD with Gradle and Docker

on:
  push:
    branches: [ "develop", "feature/#448-ci-cd" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: |
          pwd
          cd module-api
          pwd
          chmod +x gradlew
        shell: bash

      - name: gradle Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          pwd
          ./gradlew clean build test
        shell: bash

  deploy:
    needs: integration
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged == true &&
      !contains(join(github.event.pull_request.labels.*.name, ','), 'NO-Deploy')
    steps:
      - name: Deploy to Dev-EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_DEV_HOST }}
          username: ${{ secrets.AWS_DEV_USERNAME }}
          key: ${{ secrets.AWS_DEV_KEY }}
          script: |
            cd /home/ec2-user/app
            sh module-api-deploy.sh
            echo "deploy success"

